### ISSUE TITLE
[BUG]: NVFoundationLLMClient.generate_batch_async() got an unexpected keyword argument 'stop'

### ISSUE THREAD

**Issue by ashsong-nv** [nv-morpheus/Morpheus#1961]
### Version

24.10 @ e648a5b

### Which installation method(s) does this occur on?

Source

### Describe the bug.

When running a pipeline with an `LLMEngine` stage containing an `LangChainAgentNode` that uses the `NVFoundationLLMService`, I get the error message:
```
TypeError: NVFoundationLLMClient.generate_batch_async() got an unexpected keyword argument 'stop'
```
I believe this is due to a breaking change in PR #1922 to fix the `stoul` errors. Specifically, it's the removal of the `**kwargs` argument in `nvfoundation_llm_service.py.generate_batch()` and `generate_batch_async()`. I reverted the changes locally and that fixed the error.

I'm not sure if other services are impacted as well.

### Minimum reproducible example

```python
import logging

import cudf
from langchain.agents import initialize_agent
from langchain.agents import Tool

from morpheus.config import Config
from morpheus.messages import ControlMessage
from morpheus.messages import MessageMeta
from morpheus.pipeline.linear_pipeline import LinearPipeline
from morpheus.pipeline.stage_decorator import source
from morpheus.utils.logger import configure_logging
from morpheus_llm.llm import LLMEngine
from morpheus_llm.llm.nodes.extracter_node import ExtracterNode
from morpheus_llm.llm.nodes.langchain_agent_node import LangChainAgentNode
from morpheus_llm.llm.services.nvfoundation_llm_service import NVFoundationLLMService
from morpheus_llm.llm.services.utils.langchain_llm_client_wrapper import LangchainLLMClientWrapper
from morpheus_llm.llm.task_handlers.simple_task_handler import SimpleTaskHandler
from morpheus_llm.stages.llm.llm_engine_stage import LLMEngineStage


@source
def input_message() -> ControlMessage:
    cm = ControlMessage()
    cm.payload(MessageMeta(df=cudf.DataFrame({"input": "What is the square of 2?"})))
    cm.add_task(task_type="llm_engine", task={
        "task_type": "completion",
        "task_dict": {
            "input_keys": ["input"],
        },
    })
    yield cm


def main():
    # Configure Morpheus pipeline
    configure_logging(log_level=logging.DEBUG)
    config = Config()
    pipe = LinearPipeline(config)

    # Set source
    pipe.set_source(input_message(config))

    # Initialize NVFoundation LLM Service
    nvfoundation_service = NVFoundationLLMService()
    nvfoundation_client = nvfoundation_service.get_client(model_name="ai-llama3-8b")
    langchain_llm = LangchainLLMClientWrapper(client=nvfoundation_client)

    # Initialize agent
    square_number_tool = Tool(name="Square Number",
                              func=lambda x: int(x)**2,
                              description="Useful for returning the square of a number.")
    agent = initialize_agent(tools=[square_number_tool], llm=langchain_llm, verbose=True)

    # Create LLMEngine
    engine = LLMEngine()
    engine.add_node("extract_prompt", node=ExtracterNode())
    engine.add_node("agent", inputs=["/extract_prompt"], node=LangChainAgentNode(agent_executor=agent))
    engine.add_task_handler(inputs=["/agent"], handler=SimpleTaskHandler(output_columns=["output"]))

    # Add LLMEngine stage
    pipe.add_stage(LLMEngineStage(config, engine=engine))

    pipe.run()


if __name__ == "__main__":
    main()
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

Errored run

```
====Pipeline Pre-build====
====Pre-Building Segment: linear_segment_0====
====Pre-Building Segment Complete!====
====Pipeline Pre-build Complete!====
====Registering Pipeline====
====Building Pipeline====
====Building Pipeline Complete!====
====Registering Pipeline Complete!====
====Starting Pipeline====
====Building Segment: linear_segment_0====
Added source: <input_message-0; WrappedFunctionSourceStage(name=input_message, gen_fn=functools.partial(<function input_message at 0x7f18109cbd90>), compute_schema_fn=<function source.<locals>.wrapper.<locals>.compute_schema_fn_inner at 0x7f1470cc8af0>, execution_modes=(<ExecutionMode.GPU: 'GPU'>,))>
  └─> morpheus.ControlMessage
Added stage: <llm-engine-1; LLMEngineStage(engine=<morpheus_llm._lib.llm.LLMEngine object at 0x7f1470c63730>)>
  └─ morpheus.ControlMessage -> morpheus.ControlMessage
====Pipeline Started====
====Building Segment Complete!====


> Entering new AgentExecutor chain...
Error running agent: NVFoundationLLMClient.generate_batch_async() got an unexpected keyword argument 'stop'
Traceback (most recent call last):
  File "/workspace/external/morpheus/python/morpheus_llm/morpheus_llm/llm/nodes/langchain_agent_node.py", line 110, in _run_single
    return await self._agent_executor.arun(metadata=metadata, **kwargs)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 157, in awarning_emitting_wrapper
    return await wrapped(*args, **kwargs)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/base.py", line 651, in arun
    await self.acall(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 157, in awarning_emitting_wrapper
    return await wrapped(*args, **kwargs)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/base.py", line 428, in acall
    return await self.ainvoke(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/agents/agent.py", line 1481, in _acall
    next_step_output = await self._atake_next_step(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in _atake_next_step
    [
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/agents/agent.py", line 1275, in <listcomp>
    [
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/agents/agent.py", line 1303, in _aiter_next_step
    output = await self.agent.aplan(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/agents/agent.py", line 751, in aplan
    full_output = await self.llm_chain.apredict(callbacks=callbacks, **full_inputs)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/llm.py", line 310, in apredict
    return (await self.acall(kwargs, callbacks=callbacks))[self.output_key]
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 157, in awarning_emitting_wrapper
    return await wrapped(*args, **kwargs)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/base.py", line 428, in acall
    return await self.ainvoke(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/base.py", line 212, in ainvoke
    raise e
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 643, in agenerate_prompt
    return await self.agenerate(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1018, in agenerate
    output = await self._agenerate_helper(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 882, in _agenerate_helper
    raise e
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 866, in _agenerate_helper
    await self._agenerate(
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1336, in _agenerate
    await self._acall(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/workspace/external/morpheus/python/morpheus_llm/morpheus_llm/llm/services/utils/langchain_llm_client_wrapper.py", line 64, in _acall
    return await self.client.generate_async(prompt=prompt, stop=stop)
  File "/workspace/external/morpheus/python/morpheus_llm/morpheus_llm/llm/services/nvfoundation_llm_service.py", line 117, in generate_async
    return (await self.generate_batch_async(inputs=inputs, **input_dict, return_exceptions=False))[0]
TypeError: NVFoundationLLMClient.generate_batch_async() got an unexpected keyword argument 'stop'
```

Successful run after adding `**kwargs` back:

```
====Pipeline Pre-build====
====Pre-Building Segment: linear_segment_0====
====Pre-Building Segment Complete!====
====Pipeline Pre-build Complete!====
====Registering Pipeline====
====Building Pipeline====
====Building Pipeline Complete!====
====Registering Pipeline Complete!====
====Starting Pipeline====
====Building Segment: linear_segment_0====
Added source: <input_message-0; WrappedFunctionSourceStage(name=input_message, gen_fn=functools.partial(<function input_message at 0x7fac52e83d90>), compute_schema_fn=<function source.<locals>.wrapper.<locals>.compute_schema_fn_inner at 0x7fa8b2b98b80>, execution_modes=(<ExecutionMode.GPU: 'GPU'>,))>
  └─> morpheus.ControlMessage
Added stage: <llm-engine-1; LLMEngineStage(engine=<morpheus_llm._lib.llm.LLMEngine object at 0x7fa8b339ddb0>)>
  └─ morpheus.ControlMessage -> morpheus.ControlMessage
====Pipeline Started====
====Building Segment Complete!====


> Entering new AgentExecutor chain...
Thought: I need to use the Square Number tool to find the square of 2.

Action: Square Number
Action Input: 2
Observation: 4
Thought:Thought: The Square Number tool has given me the square of 2, which is 4. I need to move on to the next step to finalize the answer.

Final Answer: The square of 2 is 4.

> Finished chain.
```

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [x] I agree to follow Morpheus' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report
